# Generated by Django 5.0.1 on 2026-02-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_background_check_clear_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
